# 第 14 章承诺

Promise 提供了在 JavaScript 中处理异步编程的标准实现，而不使用回调。使用回调模式的最大副作用之一是，只需几个级别的回调，您的代码就会变得非常丑陋。

Promise 允许您比使用回调更容易地开发异步脚本。承诺代表了我们可以在未来的某个时刻处理的价值。 Promise 比回调给我们两个主要优势：

*   没有其他注册处理程序可以更改它。承诺合同是不可变的。
*   我们保证会收到该值，无论我们何时为其注册处理程序，即使它已经解决了。这与事件形成对比，因为一旦事件被触发，您将无法在以后访问其值。

我们来看下面的例子：

代码 195

```
var p2 =
  Promise.resolve("foo"); 
p2.then((res)
  => console.log(res)); 

var p = new Promise(function(resolve,
  reject) {  

  setTimeout(() => resolve(4), 2000);
});

p.then((res)
  => {  

  res += 2; 

  console.log(res);
});

p.then((res)
  => console.log(res));

```

在第一行中，我们创建一个承诺并立即解决它。这证明了第二个优点。与事件不同，我们仍然可以调用承诺并从中获取价值。接下来，我们定义一个标准的承诺，让它在两秒后解决。我们的处理程序从 promise 接收值，但不能更改 promise 本身的值。这很好，因为我们的 promise 是不可变的，并且在多次调用时总是返回相同的结果。

以下是上一个示例的输出：

代码 196

```
foo
6
4

```

到目前为止，我们只解决了承诺。当我们拒绝承诺时呢？请考虑以下代码：

代码 197

```
var p = new Promise(function(resolve,
  reject) {  

  setTimeout(() => reject("Timed out!"), 2000);
});

p.then((res)
  => console.log(res),
     (err)
  => console.log(err));

```

这次，我们在两秒钟后延迟调用`reject`。我们看到`then()`也可以接受第二个错误处理程序。

以下是上一个示例的输出：

代码 198

```
Timed out!

```

但是等等，你可以写得更加不同！请考虑以下代码：

代码 199

```
var p = new Promise(function(resolve,
  reject) {  

  setTimeout(() => reject("Timed out!"), 2000);
});

p.then((res)
  => console.log("Response:",
  res))

  .catch((err) => console.log("Error:",
  err));

```

您也可以使用 promise 中的 catch 函数。我们的输出将完全相同：

代码 200

```
Error: Timed out!

```

让我们考虑另一个例子，当发生异常时。请考虑以下代码：

代码 201

```
var p = new Promise(function(resolve,
  reject) {  

  setTimeout(() => {throw new
Error("Error
  encountered!");}, 2000);
});

p.then((res)
  => console.log("Response:",
  res))

  .catch((err) => console.log("Error:",
  err));

```

投掷`Error`与调用`reject()`相同。您可以捕获错误并相应地处理它。

以下是上一个示例的输出：

代码 202

```
Error encountered!

```